name: gcc builds

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:

        os:
          - ubuntu-18.04
          - ubuntu-20.04

        _name:
          - GCC 7
          - GCC 8
          - GCC 9

        exclude:

          - os: ubuntu-18.04
            _name: "GCC 7"

          - os: ubuntu-18.04
            _name: "GCC 8"

          - os: ubuntu-18.04
            _name: "GCC 9"

        include:

          # --------------- GCC on Linux --------------- #

          # GCC 7
          - _name: "GCC 7"
            _cxx: g++-7
            _pkg: ppa:ubuntu-toolchain-r/test

          # GCC 8
          - _name: "GCC 8"
            _cxx: g++-8
            _pkg: ppa:ubuntu-toolchain-r/test

          # GCC 9
          - _name: "GCC 9"
            _cxx: g++-9
            _pkg: ppa:ubuntu-toolchain-r/test

    steps:

      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        with:
          python-version: 3.x
          architecture: x64

      - name: ${{ matrix._name }}
        env:
          _CXX: ${{ matrix._cxx }}
          _PKG: ${{ matrix._pkg }}
        run: |
          # set the maximum number of cores supported on GitHub dockers
          JOBS=$(nproc --all)
          echo "Using ${JOBS} processors"

          # dependencies required by the CI are installed in ${BUILD_DIR}/deps/
          DEPS_DIR="deps"
          mkdir -p "${DEPS_DIR}"

          # set the proper C++ and MPI compilers
          sudo add-apt-repository "${_PKG}" -y
          sudo apt install ${_CXX} -y
          export CXX=${_CXX}
          export OMPI_CXX=${CXX}

          # install necessary packages
          sudo apt install openmpi-bin

          # set versions and URLs for requirements
          CMAKE_VER="3.17.3"
          CMAKE_URL="https://cmake.org/files/v${CMAKE_VER%.[0-9]}/cmake-${CMAKE_VER}-Linux-x86_64.tar.gz"

          SST_VER="10.0.0"
          SST_CORE_URL="https://github.com/sstsimulator/sst-core/releases/download/v${SST_VER}_Final/"

          # download sources for requirements
          # curl CMake
          curl -L ${CMAKE_URL} | tar xz -C ${DEPS_DIR}

          # upgrade CMake to a more recent version
          export PATH=$(realpath ${DEPS_DIR}/cmake-${CMAKE_VER}-Linux-x86_64/bin):${PATH}

          # curl SST Core
          curl -L ${SST_CORE_URL}sstcore-${SST_VER}.tar.gz | tar xz -C ${DEPS_DIR}
          mkdir -p ~/.sst && touch ~/.sst/sstsimulator.conf

          # install SST Core
          cd ${DEPS_DIR}/sstcore-${SST_VER} && ./configure && make -j${JOBS} all && sudo make install && cd -

          # run tests
          python -m venv .venv
          source .venv/bin/activate

          # export URL to single official list of all trusted elements and directory of SST element sources
          source setup.sh

          pip install pytest
          pytest -sv tests/cli.py
